### ISSUE TITLE
Managed to clone a repo using this module, but how does it work exactly?

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-git#11]
```
[WARNING]: Consider using git module rather than running git
```

**Comment by 030** [comment]
```
  git:
    repo: https://github.com/sensu-plugins/sensu-plugins-http.git
    dest: /tmp/sensu-plugins-http
    update: yes
```
