### ISSUE TITLE
"Force git install if version numbers do not match." task uses deprecated tests-as-filters

### ISSUE THREAD

**Issue by earchibald-lv** [geerlingguy/ansible-role-git#38]
```TASK [geerlingguy.git : Force git install if the version numbers do not match.] ***
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using
`result|version_compare` use `result is version_compare`. This feature will be
removed in version 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.```

**Comment by earchibald-lv** [comment]
(Thanks so much for putting this together! It's a lifesaver.)

**Comment by geerlingguy** [comment]
Hmm, that's from:

```yaml
- name: Force git install if the version numbers do not match.
  set_fact:
    git_reinstall_from_source: true
  when:
    - git_install_from_source_force_update
    - (git_installed_version.rc == 0) and (git_installed_version.stdout | regex_replace("^.*?([0-9\.]+)$", "\\1") | version_compare(git_version, operator="!="))
```

I wonder if I can just replace the `|` before `version_compare(` to get the notice to go away.
